version: '3.8'

services:
  welcome_web_app:
    build: ./app
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/certs:/etc/nginx/ssl
    depends_on:
      - welcome_web_app

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: arman
      POSTGRES_PASSWORD: arman_rq
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
