version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: arman
      POSTGRES_PASSWORD: arman_rq
    volumes:
     - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
