---
- name: Install and configure welcome_webapp
  hosts: localhost
  become: yes
  tasks:
    - name: Install Docker
      ansible.builtin.package:
        name: docker
        state: present

    - name: Install Docker Compose
      ansible.builtin.package:
        name: docker-compose
        state: present

    - name: Clone the Repository
      ansible.builtin.git:
        repo: git@github.com:armanot28/welcome_webapp.git
        dest: /opt/welcome_webapp
        clone: yes

    - name: Build Docker Containers
      ansible.builtin.command:
        cmd: docker-compose build
        chdir: /opt/welcome_webapp

    - name: Start Docker Containers
      ansible.builtin.command:
        cmd: docker-compose up -d
        chdir: /opt/welcome_webapp
