---
- name: Install Jenkins in CentOS 8 Stream
  hosts: localhost
  become: yes
  gather_facts: no
  vars:
    jenkins_port: 8888  

  tasks:
    - name: Add Jenkins repository
      become: yes
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
        mode: '0644'

    - name: Import Jenkins GPG key
      become: yes
      ansible.builtin.rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    - name: Install Java Development Kit (JDK)
      become: yes
      ansible.builtin.yum:
        name: java-17-openjdk-devel
        state: present

    - name: Install Jenkins
      become: yes
      ansible.builtin.yum:
        name: jenkins
        state: present

    - name: Start Jenkins Service
      become: yes
      ansible.builtin.systemd:
        name: jenkins
        state: started

    - name: Reload systemd daemon
      become: yes
      ansible.builtin.systemd:
        daemon_reload: yes
